#!/bin/sh

# --zmq-pub=tcp://127.0.0.1:18083 \

/usr/bin/monerod \
    --data-dir=/home/clay/monero/chain \
    --out-peers=64 \
    --in-peers=32 \
    --add-priority-node=node.supportxmr.com:18080 \
    --add-priority-node=nodes.hashvault.pro:18080 \
    --disable-dns-checkpoints \
    --confirm-external-bind \
    --enable-dns-blocklist \
    --detach
