#!/bin/sh

script_path="$(realpath "$0")"
script_dir="$(dirname "$script_path")"

/usr/bin/monerod \
    --data-dir="$script_dir/data" \
    --log-file="$script_dir/logs/monerod.log" \
    --confirm-external-bind \
    --p2p-bind-ip=127.0.0.1 \
    --p2p-bind-port=18080 \
    --rpc-bind-ip=127.0.0.1 \
    --rpc-bind-port=18081 \
    --detach
